name: Release to dockerhub (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - 'v*.*.*'

jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: sweagent
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run release script
          if: (github.ref == 'refs/heads/main') && (github.repository == 'princeton-nlp/SWE-agent')
          run: ./release_dockerhub.sh sweagent latest